cc_library(
    name = "utilsMock",
    hdrs = glob(["**/utils_mock.cc"]), #bazel needs to depend on headers
    visibility = ["//visibility:public"],
)

cc_library(
    name = "cec20Mock",
    hdrs = glob(["**/cec_20_test_func_mock.cc"]), #bazel needs to depend on headers
    visibility = ["//visibility:public"],
)