# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library

cc_library(
    name = "PSO",
    hdrs = glob(["**/PSO.cpp"]), #bazel needs to depend on headers
    visibility = ["//visibility:public"],
)

cc_library(
    name = "PSONovA",
    hdrs = glob(["**/PSONovA.cpp"]), #bazel needs to depend on headers
    visibility = ["//visibility:public"],
)

cc_library(
    name = "PSONovB",
    hdrs = glob(["**/PSONovB.cpp"]), #bazel needs to depend on headers
    visibility = ["//visibility:public"],
)