# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library

cc_library(
    name = "PSOalg",
    hdrs = glob(["**/PSO.cpp"]), #bazel needs to depend on headers
    visibility = ["//visibility:public"],
)