cc_test(
    name = "PSOtestsMock",
    srcs = glob(["**/PSO_test_mock.cc"]),
    deps = [
        "//src/alg:PSO",
        "//test/mock:utilsMock",
        "//test/mock:cec20Mock",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "PSOtestsNoMock",
    srcs = glob(["**/PSO_test_nomock.cc"]),
    deps = [
        "//src/alg:PSO",
        "//src/utils:UtilsLib",
        "//test/mock:cec20Mock",
        "@googletest//:gtest_main",
    ],
)


cc_test(
    name = "PSONovAtests",
    srcs = glob(["**/PSONovA_test.cc"]),
    deps = [
        "//src/alg:PSONovA",
        "//src/utils:UtilsLib",
        "//test/mock:cec20Mock",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "PSONovBtests",
    srcs = glob(["**/PSONovB_test.cc"]),
    deps = [
        "//src/alg:PSONovB",
        "//src/utils:UtilsLib",
        "//test/mock:cec20Mock",
        "@googletest//:gtest_main",
    ],
)


cc_test(
    name = "PSONovCtests",
    srcs = glob(["**/PSONovC_test.cc"]),
    deps = [
        "//src/alg:PSONovC",
        "//src/utils:UtilsLib",
        "//test/mock:cec20Mock",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "PSONovDtests",
    srcs = glob(["**/PSONovD_test.cc"]),
    deps = [
        "//src/alg:PSONovD",
        "//src/utils:UtilsLib",
        "//test/mock:cec20Mock",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "DEtestMock",
    srcs = glob(["**/DE_test_mock.cc"]),
    deps = [
        "//src/alg:DE",
        "//test/mock:utilsMock",
        "//test/mock:cec20Mock",
        "@googletest//:gtest_main",
    ],
)



