cc_test(
    name = "PSOtests",
    srcs = glob(["**/PSO_test.cc"]),
    deps = [
        "//src/alg:PSOalg",
        "//test/mock:utilsMock",
        "//test/mock:cec20Mock",
        "@googletest//:gtest_main",
    ],
)


