# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library

cc_library(
    name = "UtilsLib",
    hdrs = glob(["**/utils.cpp"]), #bazel needs to depend on headers
    visibility = ["//visibility:public"],
)